#!/usr/bin/env node
/**
 * Generate docs/ROUTE_INVENTORY.md from every route.ts under apps/web/src/app/api.
 *
 * Output is a Markdown table listing: path, exported HTTP methods, whether the
 * route mutates data, its auth posture, any scope check, and whether the body
 * is validated via Zod.
 *
 * Heuristics (intentionally simple, can be fooled by unusual code):
 *   - Method exports detected via `export async function (GET|POST|PATCH|PUT|DELETE)`
 *   - "Mutates" = any of POST/PATCH/PUT/DELETE
 *   - "Auth" — calls getOrgId() or getCurrentUser() or requireAuth() or reads token
 *   - "Org scope" — has at least one `.eq("org_id", orgId)` in the file
 *   - "Validated" — imports parseBody or previewRequestSchema or similar
 *
 * Usage:
 *   node --experimental-strip-types scripts/generate-route-inventory.ts
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const REPO_ROOT = join(import.meta.dirname, "..");
const API_ROOT = join(REPO_ROOT, "apps", "web", "src", "app", "api");
const OUTPUT = join(REPO_ROOT, "docs", "ROUTE_INVENTORY.md");

interface RouteInfo {
  path: string; // URL path reconstructed from directory layout
  file: string;
  methods: string[];
  mutates: boolean;
  auth: "required" | "optional" | "public";
  orgScoped: boolean;
  validated: boolean;
  emitsEvents: boolean;
  note: string;
}

function walk(dir: string, collected: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, collected);
    else if (entry === "route.ts" || entry === "route.tsx") collected.push(full);
  }
  return collected;
}

function toUrlPath(file: string): string {
  const rel = relative(API_ROOT, file).replace(/\\/g, "/");
  const segs = rel.split("/");
  segs.pop(); // drop route.ts
  return "/api/" + segs.join("/");
}

function analyzeFile(file: string): RouteInfo {
  const src = readFileSync(file, "utf8");
  const methodRegex = /^export\s+async\s+function\s+(GET|POST|PATCH|PUT|DELETE)\s*\(/gm;
  const methods: string[] = [];
  for (const match of src.matchAll(methodRegex)) methods.push(match[1]);

  const mutates = methods.some((m) => ["POST", "PATCH", "PUT", "DELETE"].includes(m));

  let auth: RouteInfo["auth"] = "public";
  if (/\brequireAuth\b/.test(src)) auth = "required";
  else if (/\bgetCurrentUser\b/.test(src)) auth = "optional";
  else if (/\bgetOrgId\b/.test(src)) auth = "required";
  // Token-gated public endpoints are still "public" from the auth system's
  // perspective; annotate in the note column instead.

  const orgScoped = /eq\(\s*["']org_id["']/.test(src);
  const validated =
    /parseBody\s*\(/.test(src) ||
    /previewRequestSchema/.test(src) ||
    /\.safeParse\s*\(/.test(src);
  const emitsEvents = /emitEvent\s*\(/.test(src);

  const notes: string[] = [];
  if (/assertEstimateToken/.test(src)) notes.push("HMAC token-gated");
  if (/runtime\s*=\s*["']nodejs["']/.test(src) === false) notes.push("no runtime decl");
  if (file.includes("webhooks/")) notes.push("webhook");
  if (file.includes("/sync/")) notes.push("cron/sync");

  return {
    path: toUrlPath(file),
    file: relative(REPO_ROOT, file).replace(/\\/g, "/"),
    methods: methods.sort(),
    mutates,
    auth,
    orgScoped,
    validated,
    emitsEvents,
    note: notes.join(", "),
  };
}

function markdown(routes: RouteInfo[]): string {
  const header = `# CallscraperCRM API Route Inventory

Auto-generated by \`scripts/generate-route-inventory.ts\`. Do not edit by hand —
re-run after adding or moving routes.

- **${routes.length} routes total**
- **${routes.filter((r) => r.mutates).length} mutate data** (POST/PATCH/PUT/DELETE)
- **${routes.filter((r) => r.orgScoped).length} apply org_id scoping**
- **${routes.filter((r) => r.validated).length} validate body via Zod**
- **${routes.filter((r) => r.auth === "required").length} require auth**
- **${routes.filter((r) => r.auth === "public").length} are public** (including token-gated)

## Reading this table

- **Mutates**: data-changing operations. Every mutating route should scope by org.
- **Scoped**: file contains \`.eq("org_id", orgId)\`. Not scoping a mutating route is a multi-tenancy bug.
- **Validated**: body is parsed by a Zod schema. Missing validation on a mutating route is an input-handling bug.
- **Auth**: how the route asserts caller identity.
- **Events**: route emits to the \`events\` table, fueling the automation engine.

`;

  let body = "| Path | Methods | Mutates | Scoped | Validated | Auth | Events | Notes |\n";
  body += "|------|---------|---------|--------|-----------|------|--------|-------|\n";
  for (const r of routes.sort((a, b) => a.path.localeCompare(b.path))) {
    body +=
      `| \`${r.path}\` ` +
      `| ${r.methods.join(" ")} ` +
      `| ${r.mutates ? "✓" : ""} ` +
      `| ${r.orgScoped ? "✓" : r.mutates ? "**⚠ missing**" : ""} ` +
      `| ${r.validated ? "✓" : r.mutates ? "—" : ""} ` +
      `| ${r.auth} ` +
      `| ${r.emitsEvents ? "✓" : ""} ` +
      `| ${r.note} |\n`;
  }

  return header + body;
}

function main() {
  if (!existsSync(API_ROOT)) {
    console.error("API_ROOT not found:", API_ROOT);
    process.exit(1);
  }
  const files = walk(API_ROOT);
  const routes = files.map(analyzeFile);
  mkdirSync(join(REPO_ROOT, "docs"), { recursive: true });
  writeFileSync(OUTPUT, markdown(routes));
  console.log(`Wrote ${OUTPUT} (${routes.length} routes)`);
}

main();
